#ifndef _DUMMY_MODULE_IOCTL_H
#define _DUMMY_MODULE_IOCTL_H

#include <linux/ioctl.h>
#define DUMMY_MODULE_NOF_DEVICES 5
#define DUMMY_MODULE_NOF_PIPES 5
#define DUMMY_MODULE_PIPE_BUFFER_SIZE 128
#define DUMMY_MODULE_MAGIC 'j'

#define DUMMY_MODULE_GET_PR_INFO _IOWR(DUMMY_MODULE_MAGIC,0,int)
#define DUMMY_MODULE_MAX_IO_CMD 0
#endif
